core-$(ARCH_CONFIG_GET_ARCH) += $(PWD)/arch/$(ARCH)/module-lib/

# obj-y := $(PWD)/arch/$(ARCH)/module-lib/built-in.o
# all:$(obj-y)

# $(obj-y):
# 	make -C $(@D)
# %.o:%.c FORCE
# 	gcc -c -o $@ $< -I. -I${PWD}/include